### ISSUE TITLE
Добавить подгрузку рецептов коктейлей с помощью AJAX

### ISSUE THREAD

**Issue by tim-tv** [TitovArtem/cocktails#23]
Добавить кнопку для подгрузки рецептов коктейлей на главной страницы с помощью AJAX запросов. Если выведен весь список рецептов для заданного запроса, то необходимо удалить кнопку.

**Comment by TitovArtem** [comment]
Исправить баг при загрузке индексной страницы после нажатия назад с страницы рецепта в Chrome. Вместо индексной страницы отображается число рецептов на странице.

**Comment by tim-tv** [comment]
Исправить баг при переходе на индексную страницу с детализированной страницы рецепта в Chrome. Отображается количество рецептов на странице.
